In [1]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
newarr = arr.reshape(2,2, -1)
print(newarr)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [3]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6]])
newarr = arr.reshape(-1)
print(newarr)

SyntaxError: invalid non-printable character U+00A0 (1804229152.py, line 1)

In [4]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6]])

print(newarr)

SyntaxError: invalid non-printable character U+00A0 (1804229152.py, line 1)

In [9]:
import numpy as np
arr = np.array([[2,4,5,4,],[4,6,7,8,8]])
newarr = arr.reshape(-1)
print(newarr)


[list([2, 4, 5, 4]) list([4, 6, 7, 8, 8])]


C:\Users\PC\AppData\Local\Temp\ipykernel_8072\3895036248.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([[2,4,5,4,],[4,6,7,8,8]])


In [10]:
import numpy as np
arr =np.array([3,5,4,4,6])
for x  in arr :
    print(x)

3
5
4
4
6


In [11]:
import numpy as np
arr=np.array ([[3,4,5,6,4,3],[4,4,6,7,4,3,]])
for x in arr:
    print(x)

[3 4 5 6 4 3]
[4 4 6 7 4 3]


In [12]:
import numpy as np
arr=np.array ([[3,4,5,6,4,3],[4,4,6,7,4,3,]])
for x in arr:
    for y in x:
        print(y)

3
4
5
6
4
3
4
4
6
7
4
3


In [13]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
    print(x)
    

SyntaxError: invalid non-printable character U+00A0 (1613663500.py, line 2)

In [15]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[3,4,6],[6,7,8]]])
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[3 4 6]
 [6 7 8]]


In [16]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[3,4,6],[6,7,8]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
3
4
6
6
7
8


In [18]:
import numpy as np
arr = np.array([[1,2],[3,4],[5,6],[7,8]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [19]:
import numpy as np
arr= np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[:,::2]):
    print(x)

1
3
5
7


In [20]:
import numpy as np
arr =np.array([1,2,3,4,5])
for idx, x in np.ndenumerate(arr):
    print(idx,x)

SyntaxError: invalid non-printable character U+00A0 (3424725394.py, line 3)